apiVersion: v1
kind: Service
metadata:
  name: k-query
  labels:
    app: k-query
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: k-query
---
apiVersion: v1
kind: Service
metadata:
  name: k-query-internal
  labels:
    app: k-query
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: k-query